on: [push]

name: PHPUnit
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            phpunit: 6.5.14

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:${{ matrix.phpunit }}
      - name: PHPUnit Tests
        run: |
          phpunit
